Rails.application.config.assets.precompile += %w( home.js )
Rails.application.config.assets.precompile += %w( vehiculos.js )
Rails.application.config.assets.precompile += %w( bootstrap-filestyle.min.js )
Rails.application.config.assets.precompile += %w( activeadmin.js )
Rails.application.config.assets.precompile += %w( filtro.js )
Rails.application.config.assets.precompile += %w( bootstrap-slider.js )